### ISSUE TITLE
Upgrade from 0.5 to 0.7.2 failed

### ISSUE THREAD

**Issue by pawelpabich** [parautenbach/TeamCity-HipChat-Notifier#42]
Hi,

I decided to upgrade HipChat notifier on our 8.1.1 Team City server and now the HipChat page is empty most of the time. If I'm persistent enough :) and hit F5 a lot I can be lucky and end up with a populate screen. This is what I found in TC log:

```
 jetbrains.buildServer.SERVER - Unhandled exception occurred while calling method fillModel of HipChatConfigurationPageExtension[myIncludeUrl='/plugins/HipChat Notifier/adminSettings.jsp', myPluginName='hipChat', myPlaceId=/admin/admin.html#ADMIN_SERVER_CONFIGURATION@TAB] extension. 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at jetbrains.buildServer.web.impl.PagePlaceImpl$ProxyHandler.invokeExtensionMethodUnsafe(PagePlaceImpl.java:22)
	at jetbrains.buildServer.web.impl.PagePlaceImpl$ProxyHandler.invoke(PagePlaceImpl.java:21)
	at com.sun.proxy.$Proxy32.fillModel(Unknown Source)
	at jetbrains.buildServer.web.impl.PageExtensionsInterceptor.fillModel(PageExtensionsInterceptor.java:10)
	at jetbrains.buildServer.web.impl.PageExtensionsInterceptor.processCustomTabs(PageExtensionsInterceptor.java:35)
	at jetbrains.buildServer.web.impl.PageExtensionsInterceptor.fillModel(PageExtensionsInterceptor.java:66)
	at jetbrains.buildServer.web.impl.PageExtensionsInterceptor.postHandle(PageExtensionsInterceptor.java:59)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:801)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:13)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at jetbrains.buildServer.web.ParametersProviderCalculationContextFilter.doFilter(ParametersProviderCalculationContextFilter.java:5)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at jetbrains.buildServer.web.DisableSessionIdFromUrlFilter.doFilter(DisableSessionIdFromUrlFilter.java:2)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at jetbrains.buildServer.web.DiagnosticFilter.doFilter(DiagnosticFilter.java:23)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at jetbrains.buildServer.web.ResponseFragmentFilter.doFilter(ResponseFragmentFilter.java:10)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
	at com.whatsthatlight.teamcity.hipchat.Utils.getRooms(Utils.java:55)
	at com.whatsthatlight.teamcity.hipchat.HipChatConfigurationPageExtension.fillModel(HipChatConfigurationPageExtension.java:85)
	... 44 more
[2015-01-22 08:41:42,911]   INFO - .impl.agent.AgentZipLookupTask - Build agent distribution version is set to 29939, hash=SHA-16SLeqiSuraaL7gbcktmMvJXPF7M= 
[2015-01-22 08:42:07,786]   WARN -   jetbrains.buildServer.SERVER - Unhandled exception occurred while calling method fillModel of HipChatConfigurationPageExtension[myIncludeUrl='/plugins/HipChat Notifier/adminSettings.jsp', myPluginName='hipChat', myPlaceId=/admin/admin.html#ADMIN_SERVER_CONFIGURATION@TAB] extension. 
java.lang.reflect.InvocationTargetException

```

**Comment by parautenbach** [comment]
Hi Pawel

Sorry about that, but I can't seem to reproduce this. Strange, because v0.7.2 was built against TC 8.1.1 exactly. Any chance you could upgrade TC to 8.1.5 and try v0.8.0? Or are you planning on upgrading to TC 9 at some stage? I have upgraded our server at work last week, so I'll be updating the plugin to work against it. 

Did you remove your TeamCity directory completlye before the upgrade? It's recommended by the Jetbrains team. It sounds to me like you have two different JARs containing the same classes, and upon refresh its anybody's guess which one gets reflected/loaded. Note point 2 under the [manual upgrade instructions](https://confluence.jetbrains.com/display/TCD8/Upgrade).

**Comment by pawelpabich** [comment]
Hi,

No worries. I have upgraded TC to 8.1.5 and then it worked.

**Comment by parautenbach** [comment]
Glad you won! :-)
