### ISSUE TITLE
Install fails on Teamcity 8.1.5, java 1.7.0_45 openjdk

### ISSUE THREAD

**Issue by ssansom** [parautenbach/TeamCity-HipChat-Notifier#56]
0.8.0 works fine on our setup, however,  it appears as though 0.9.1 is failing to install with this error:

ERROR - gins.spring.SpringPluginLoader - Failed to initialize spring context for plugin HipChat Notifier 
java.lang.ClassFormatError: Illegal local variable table length 5 in method com.whatsthatlight.teamcity.hipchat.HipChatConfiguration.getEvents()Lcom/whatsthatlight/teamcity/hipchat/HipChatEventConfiguration;
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2493)
	at java.lang.Class.getDeclaredConstructors(Class.java:1901)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:227)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:930)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:903)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:580)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at jetbrains.buildServer.plugins.spring.SpringPluginLoader.pluginClassesLoaded(SpringPluginLoader.java:72)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:121)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:71)
	at com.sun.proxy.$Proxy8.pluginClassesLoaded(Unknown Source)
	at jetbrains.buildServer.plugins.PluginManagerImpl$2.visitPlugin(PluginManagerImpl.java:122)
	at jetbrains.buildServer.plugins.PluginsCollection.foreachLoadedPlugins(PluginsCollection.java:107)
	at jetbrains.buildServer.plugins.PluginManagerImpl.firePluginClassesLoaded(PluginManagerImpl.java:120)
	at jetbrains.buildServer.plugins.PluginManagerImpl.loadPlugins(PluginManagerImpl.java:80)
	at jetbrains.buildServer.web.plugins.PluginManagerConfigurator.initializePlugins(PluginManagerConfigurator.java:14)
	at jetbrains.buildServer.web.impl.BuildServerConfigurator.loadConfiguration(BuildServerConfigurator.java:30)
	at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet$WebApplicationCreatorAndDestroyer.createApplication(TeamCityDispatcherServlet.java:3)
	at jetbrains.buildServer.maintenance.StartupProcessor.doApplicationStarting(StartupProcessor.java:189)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStage(StartupProcessor.java:505)
	at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStageSafe(StartupProcessor.java:61)
	at jetbrains.buildServer.maintenance.StartupProcessor.processTeamCityLifecycle(StartupProcessor.java:608)
	at jetbrains.buildServer.maintenance.StartupProcessor.access$000(StartupProcessor.java:12)
	at jetbrains.buildServer.maintenance.StartupProcessor$1.run(StartupProcessor.java)
	at java.lang.Thread.run(Thread.java:744)

**Comment by parautenbach** [comment]
Due to a difference in libraries included in the TeamCity distribution that is also used by the plugin, it is very unlikely that v0.9.1 will work on TC versions before 9.0.2. Kindly see the compatibility notes in the [README](https://github.com/parautenbach/TeamCity-HipChat-Notifier/blob/master/README.md).

**Comment by ssansom** [comment]
Yes. Sorry I must have misread the notes, I thought TC 9 support was added, but I didn't realize TC 8 support as dropped.

**Comment by parautenbach** [comment]
It would be possible to build against different TC versions, but the TC team changes libraries sometimes even between minor and revision changes. It would just make it hard for me to keep up, so I've generally opted for rolling forwards. You could alternatively run an older suitable version. Is there a specific feature you would miss then? Would it be possible to upgrade your TC server?

**Comment by ssansom** [comment]
AFAIK there's no specific feature in 0.9 that we need. I just wanted to use
the latest if possible. I've already installed 0.8.0 instead.  We'll be
upgrading to TC 9 fairly soon anyway.

**Comment by parautenbach** [comment]
:+1:

**Comment by parautenbach** [comment]
The error you got could also the due to #58.

**Comment by parautenbach** [comment]
Fixed in [v0.9.2](https://github.com/parautenbach/TeamCity-HipChat-Notifier/releases/tag/0.9.2).
