### ISSUE TITLE
OpenJDK 1.8 and SSL/TLS error

### ISSUE THREAD

**Issue by dwerder** [parautenbach/TeamCity-HipChat-Notifier#69]
Hello,

first want to say thank you for the plugin. We recently did a upgrade of teamcity to 9.1.4 and to JDK 1.8.0_65 ( OpenJDK Runtime Environment (build 1.8.0_65-b17) )

JDK 1.8 is supported by teamcity since 9.1.

But we get the following error:

```
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [jetbrains.buildServer.nuget.server.feed.impl.FeedHttpClientHolder]: Constructor threw exception; nested exception is java.lang.IllegalState
Exception: Failure initializing default SSL context
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:164)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:125)
        at jetbrains.buildServer.spring.InstantiationStrategySelector$1.instantiate(InstantiationStrategySelector.java:77)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:270)
        ... 32 more
Caused by: java.lang.IllegalStateException: Failure initializing default SSL context
        at org.apache.http.conn.ssl.SSLSocketFactory.createDefaultSSLContext(SSLSocketFactory.java:211)
        at org.apache.http.conn.ssl.SSLSocketFactory.<init>(SSLSocketFactory.java:333)
        at org.apache.http.conn.ssl.SSLSocketFactory.getSocketFactory(SSLSocketFactory.java:165)
        at org.apache.http.impl.conn.SchemeRegistryFactory.createDefault(SchemeRegistryFactory.java:45)
        at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.<init>(ThreadSafeClientConnManager.java:98)
        at jetbrains.buildServer.nuget.server.feed.impl.FeedHttpClientHolder.createHttpClient(FeedHttpClientHolder.java:60)
        at jetbrains.buildServer.nuget.server.feed.impl.FeedHttpClientHolder.<init>(FeedHttpClientHolder.java:44)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
        ... 35 more
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: TLS, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$TLSContext)
        at java.security.Provider$Service.newInstance(Provider.java:1617)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at org.apache.http.conn.ssl.SSLSocketFactory.createSSLContext(SSLSocketFactory.java:202)
        at org.apache.http.conn.ssl.SSLSocketFactory.createDefaultSSLContext(SSLSocketFactory.java:209)
        ... 46 more
Caused by: java.lang.IllegalArgumentException: jdk.tls.client.protocols: TLSv is not a standard SSL/TLS protocol name
        at sun.security.ssl.SSLContextImpl$CustomizedSSLContext.<clinit>(SSLContextImpl.java:669)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.security.Provider$Service.getImplClass(Provider.java:1634)
        at java.security.Provider$Service.newInstance(Provider.java:1592)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at org.apache.http.conn.ssl.SSLContexts.createDefault(SSLContexts.java:54)
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:719)
        at com.whatsthatlight.teamcity.hipchat.HipChatApiProcessor.createClient(HipChatApiProcessor.java:195)
        at com.whatsthatlight.teamcity.hipchat.HipChatApiProcessor.getEmoticons(HipChatApiProcessor.java:73)
        at com.whatsthatlight.teamcity.hipchat.HipChatEmoticonCache.reload(HipChatEmoticonCache.java:42)
        at com.whatsthatlight.teamcity.hipchat.HipChatConfigurationController.initialise(HipChatConfigurationController.java:296)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1682)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1621)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1550)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
        ... 29 more
Caused by: java.lang.IllegalArgumentException: TLSv
        at sun.security.ssl.ProtocolVersion.valueOf(ProtocolVersion.java:187)
        at sun.security.ssl.SSLContextImpl$CustomizedSSLContext.<clinit>(SSLContextImpl.java:667)
        ... 50 more
```

**Comment by dwerder** [comment]
Sorry. It was a config error on our behalf.
Missused `-Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2"`
